# Generated by Django 2.2.1 on 2019-05-25 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='companions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='companions', to='backend.UserDetail'),
        ),
    ]
